namespace VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

public class ApiCustomLanguageModel
{
    public string id { get; set; } = string.Empty;
    public string name { get; set; } = string.Empty;
    public string language { get; set; } = string.Empty;
    public string state { get; set; } = string.Empty;
    public string languageModelId { get; set; } = string.Empty;
    public List<ApiCustomLanguageModelTrainingDataFileModel> files { get; set; } = new List<ApiCustomLanguageModelTrainingDataFileModel>();
    public bool hasCrisEdits { get; set; }
    public bool isAutoGeneratedModel { get; set; }
}
