namespace VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

public class ApiCustomLanguageModel
{
    public string Id { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Language { get; set; } = string.Empty;
    public string State { get; set; } = string.Empty;
    public string LanguageModelId { get; set; } = string.Empty;
    public List<ApiCustomLanguageModelTrainingDataFileModel> Files { get; set; } = new List<ApiCustomLanguageModelTrainingDataFileModel>();
    public bool HasCrisEdits { get; set; }
    public bool IsAutoGeneratedModel { get; set; }
}