namespace VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

public class ApiLanguageModelDataModel
{
    /// <summary>モデルID（GUID）</summary>
    public string? id { get; set; }

    /// <summary>モデル名</summary>
    public string? name { get; set; }

    /// <summary>対応言語</summary>
    public string? language { get; set; }

    /// <summary>モデルの状態</summary>
    public string? state { get; set; }

    /// <summary>言語モデルID（GUID）</summary>
    public string? languageModelId { get; set; }

    /// <summary>関連するファイルのリスト</summary>
    public List<ApiLanguageModelFileMetadataModel> files { get; set; } = new List<ApiLanguageModelFileMetadataModel>();

    /// <summary>CRIS 編集があるかどうか</summary>
    public bool hasCrisEdits { get; set; }

    /// <summary>自動生成モデルかどうか</summary>
    public bool isAutoGeneratedModel { get; set; }
}