using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

namespace VideoIndexerAccess.Repositories.DataModel
{
    public class CustomLanguageModel
    {
        public string Id { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string Language { get; set; } = string.Empty;
        public string State { get; set; } = string.Empty;
        public string LanguageModelId { get; set; } = string.Empty;
        public List<CustomLanguageModelTrainingDataFileModel> Files { get; set; } = [];
        public bool HasCrisEdits { get; set; }
        public bool IsAutoGeneratedModel { get; set; }
    }
}
