using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VideoIndexerAccess.Repositories.DataModel
{
    public class LanguageModelDataModel
    {
        /// <summary>モデルID（GUID）</summary>
        public string? Id { get; set; }

        /// <summary>モデル名</summary>
        public string? Name { get; set; }

        /// <summary>対応言語</summary>
        public string? Language { get; set; }

        /// <summary>モデルの状態</summary>
        public string? State { get; set; }

        /// <summary>言語モデルID（GUID）</summary>
        public string? LanguageModelId { get; set; }

        /// <summary>関連するファイルのリスト</summary>
        public List<LanguageModelFileMetadataModel> Files { get; set; } = new List<LanguageModelFileMetadataModel>();

        /// <summary>CRIS 編集があるかどうか</summary>
        public bool HasCrisEdits { get; set; }

        /// <summary>自動生成モデルかどうか</summary>
        public bool IsAutoGeneratedModel { get; set; }
    }
}
