using VideoIndexerAccess.Repositories.DataModel;
using VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

namespace VideoIndexerAccess.Repositories.DataModelMapper;

public interface ITextualSummarizationJobWithSummaryContentContractMapper
{
    TextualSummarizationJobWithSummaryContentContractModel MapFrom(ApiAOAITextualSummarizationJobWithSummaryContentContractModel model);
    ApiAOAITextualSummarizationJobWithSummaryContentContractModel MapTo(TextualSummarizationJobWithSummaryContentContractModel model);
}