using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VideoIndexerAccess.Repositories.DataModel;
using VideoIndexerAccessCore.VideoIndexerClient.ApiModel;

namespace VideoIndexerAccess.Repositories.DataModelMapper
{
    public class LanguageModelDataMapper : ILanguageModelDataMapper
    {
        private readonly ILanguageModelFileMetadataMapper _languageModelFileMetadataMapper;

        public LanguageModelDataMapper(ILanguageModelFileMetadataMapper languageModelFileMetadataMapper)
        {
            _languageModelFileMetadataMapper = languageModelFileMetadataMapper;
        }

        public LanguageModelDataModel MapFrom(ApiLanguageModelDataModel model)
        {
            return new LanguageModelDataModel
            {
                Id = model.id,
                Name = model.name,
                Language = model.language,
                State = model.state,
                LanguageModelId = model.languageModelId,
                Files = model.files.Select(_languageModelFileMetadataMapper.MapFrom).ToList(),
                HasCrisEdits = model.hasCrisEdits,
                IsAutoGeneratedModel = model.isAutoGeneratedModel
            };
        }

        public ApiLanguageModelDataModel MapToApiLanguageModelDataModel(LanguageModelDataModel model)
        {
            return new ApiLanguageModelDataModel
            {
                id = model.Id,
                name = model.Name,
                language = model.Language,
                state = model.State,
                languageModelId = model.LanguageModelId,
                files = model.Files.Select(_languageModelFileMetadataMapper.MapToApiLanguageModelFileMetadataModel).ToList(),
                hasCrisEdits = model.HasCrisEdits,
                isAutoGeneratedModel = model.IsAutoGeneratedModel
            };
        }
    }
}
